databases:
  - name: recipe_app
    databaseName: recipe_app_topu
    user: recipe_app_topu_user

services:
  - type: web
    name: food-recipe
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe_app_topu
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false